# Generated by Django 3.1.6 on 2021-02-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('email_address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=200)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbConnector.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbConnector.contactinfo')),
            ],
        ),
    ]
